version: 0.1
log:
  level: debug
  formatter: json
  fields:
    service: registry
    environment: development
storage:
  cache:
    layerinfo: redis
  s3:
    accesskey: 
    secretkey: 
    region: 
    bucket: 
    encrypt: false
    secure: true
    v4auth: true
    chunksize: 5242880
http:
  addr: :5000
  secret: 
  debug:
    addr: localhost:5001
  tls:
    certificate: /go/src/github.com/docker/distribution/certs/registry.crt
    key: /go/src/github.com/docker/distribution/certs/registry.pem
    # clientcas:
    #   - /go/src/github.com/docker/distribution/certs/clients.crt
redis:
  addr: localhost:6379
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s